tests: Fix the file system test
The file system test executed the ls command by directly writing and
reading to/from the SSH connection. However, after the Yocto (and the
resulting systemd) update, the connection now returns OSC 3008
sequences. Use "Run Command" keyword instead to filter out these
sequences automatically, and add a short sleep after the commands. This
sleep  allows the command to terminate properly, otherwise the following
error can be seen in the tests:

ChannelException: ChannelException(2, 'Connect failed')

This most likely happens because Sulka by default heavily limits the
concurrent connections.